export const APP_CONFIG = {
  edition: import.meta.env.VITE_EDITION_NAME || 'Fin de semana',
  closeLabel: import.meta.env.VITE_CLOSE_LABEL || 'Por definir',
  closeTime: import.meta.env.VITE_CLOSE_TIME || '',
  firstPrize: import.meta.env.VITE_FIRST_PRIZE || 'Por definir',
  secondPrize: import.meta.env.VITE_SECOND_PRIZE || 'Por definir',
} as const

export const TEAM_LOGOS: Record<string, string> = {
  America: '/logos_equipos/america.svg',
  América: '/logos_equipos/america.svg',
  'Club America': '/logos_equipos/america.svg',
  Atlas: '/logos_equipos/atlas.svg',
  Atlante: '/logos_equipos/atlante.svg',
  'Atletico de San Luis': '/logos_equipos/san_luis.svg',
  'Atl. San Luis': '/logos_equipos/san_luis.svg',
  'CD Guadalajara': '/logos_equipos/chivas.svg',
  Chivas: '/logos_equipos/chivas.svg',
  Guadalajara: '/logos_equipos/chivas.svg',
  'Cruz Azul': '/logos_equipos/cruz_azul.svg',
  Juarez: '/logos_equipos/juarez.svg',
  Juárez: '/logos_equipos/juarez.svg',
  'FC Juarez': '/logos_equipos/juarez.svg',
  Leon: '/logos_equipos/leon.svg',
  León: '/logos_equipos/leon.svg',
  'Club Leon': '/logos_equipos/leon.svg',
  Monterrey: '/logos_equipos/monterrey.svg',
  Necaxa: '/logos_equipos/necaxa.svg',
  Pachuca: '/logos_equipos/pachuca.svg',
  Puebla: '/logos_equipos/puebla.svg',
  Pumas: '/logos_equipos/pumas.svg',
  'Pumas UNAM': '/logos_equipos/pumas.svg',
  'UNAM Pumas': '/logos_equipos/pumas.svg',
  'U.N.A.M.': '/logos_equipos/pumas.svg',
  'Club Universidad Nacional': '/logos_equipos/pumas.svg',
  Queretaro: '/logos_equipos/queretaro.svg',
  Querétaro: '/logos_equipos/queretaro.svg',
  Santos: '/logos_equipos/santos.svg',
  'Santos Laguna': '/logos_equipos/santos.svg',
  Tigres: '/logos_equipos/tigres.svg',
  'Tigres UANL': '/logos_equipos/tigres.svg',
  'UANL Tigres': '/logos_equipos/tigres.svg',
  'Club Tigres': '/logos_equipos/tigres.svg',
  'Tigres de la UANL': '/logos_equipos/tigres.svg',
  Tijuana: '/logos_equipos/tijuana.svg',
  Toluca: '/logos_equipos/toluca.svg',
}
